// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD9m3SUw_0Bi63dGrRA8_0oLJdCRKAjUE',
    appId: '1:383981743617:web:4ecfed302e765bd0559a00',
    messagingSenderId: '383981743617',
    projectId: 'flutix-app-dec2e',
    authDomain: 'flutix-app-dec2e.firebaseapp.com',
    storageBucket: 'flutix-app-dec2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0CI_ekCKwkA1mHQEazxt_iAwp7ZOJdAg',
    appId: '1:383981743617:android:b2337534b96e892e559a00',
    messagingSenderId: '383981743617',
    projectId: 'flutix-app-dec2e',
    storageBucket: 'flutix-app-dec2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB56uF1tRjHa6MHJIGa19r4HSP3MfApCwA',
    appId: '1:383981743617:ios:9f813b8b61a55f0a559a00',
    messagingSenderId: '383981743617',
    projectId: 'flutix-app-dec2e',
    storageBucket: 'flutix-app-dec2e.appspot.com',
    iosBundleId: 'com.example.flutix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB56uF1tRjHa6MHJIGa19r4HSP3MfApCwA',
    appId: '1:383981743617:ios:9f9e16cf1915cb46559a00',
    messagingSenderId: '383981743617',
    projectId: 'flutix-app-dec2e',
    storageBucket: 'flutix-app-dec2e.appspot.com',
    iosBundleId: 'com.example.flutix.RunnerTests',
  );
}
